### ISSUE TITLE
Mongoose slave nodes doesn't inherit serviceAccountName from master node

### ISSUE THREAD

**Issue by dadlex** [emc-mongoose/mongoose-helm-charts#12]
While running mongoose in distributed mode, only master node has the right  serviceAccountName. All slave nodes have  serviceAccountName set to "default".

**Comment by veronikaKochugova** [comment]
I can't reproduce :( It works:
```
helm install --dry-run --debug --name m emc-mongoose/mongoose --set "serviceAccount=other" --set "replicas=4" --namespace mongoose
```

**Comment by dadlex** [comment]
While Mongoose does start in distributed mode and all pods are running, it seems that the workload is only done by the master node, while all slaves are blocked due to authentication issues.
![image](https://user-images.githubusercontent.com/3900954/64246845-411a8d00-cf16-11e9-90de-6a95def3c745.png)
